import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { dashboardApi, alertApi } from "../../api/services";
import { MetricCard } from "../../components/dashboard/MetricCard";
import { Card, CardHeader } from "../../components/ui/Card";
import { ErrorPanel } from "../../components/ui/ErrorPanel";
import { Skeleton } from "../../components/ui/Skeleton";
import { StatusBadge } from "../../components/ui/StatusBadge";
import { formatCurrency, labelize } from "../../utils/format";
export function DashboardPage() { const metrics = useQuery({ queryKey: ["dashboard"], queryFn: dashboardApi.metrics }); const alerts = useQuery({ queryKey: ["alerts", "active", 5], queryFn: () => alertApi.active({ limit: 5 }) }); if (metrics.isLoading) return <Skeleton rows={8} />; if (metrics.isError) return <ErrorPanel error={metrics.error} />; const data = metrics.data; if (!data) return <ErrorPanel error={new Error("Dashboard metrics unavailable")} />; return <div className="page-stack"><div className="page-title"><p className="eyebrow">Action-first command center</p><h1>Operational Control Dashboard</h1><span>Prioritized by pending approvals, settlement blockers, courier delays, refunds and alerts.</span></div><section className="metric-grid"><MetricCard label="Pending Preauth" value={data.pendingCounts.preauth} tone="warning" hint="Claims awaiting insurer preauth" /><MetricCard label="Final Approval" value={data.pendingCounts.finalApproval} tone="warning" /><MetricCard label="Settlement Pending" value={data.pendingCounts.settlements} tone="danger" /><MetricCard label="Courier >60 days" value={data.delayedClaims.over60Days} tone="danger" /><MetricCard label="Refund Pending" value={data.pendingDepositRefunds} tone="warning" /><MetricCard label="Active Alerts" value={data.activeAlertsCount} tone="danger" /><MetricCard label="Settled Amount" value={formatCurrency(data.financials.totalSettledAmount)} tone="success" /></section><div className="two-column"><Card><CardHeader title="Claims ageing" eyebrow="Workflow bottlenecks" /><div className="age-grid"><MetricCard label="< 30 days" value={data.ageingSummary.under30Days} /><MetricCard label="30-60 days" value={data.ageingSummary.between30And60Days} tone="warning" /><MetricCard label="60-90 days" value={data.ageingSummary.between60And90Days} tone="danger" /><MetricCard label="> 90 days" value={data.ageingSummary.over90Days} tone="danger" /></div></Card><Card><CardHeader title="Active operational alerts" eyebrow="Requires action" action={<Link to="/alerts">View all</Link>} />{alerts.data?.data.map((alert) => <div className="alert-row" key={alert._id}><StatusBadge value={alert.severity} compact /><div><strong>{labelize(alert.type)}</strong><span>{alert.message}</span></div></div>)}</Card></div><Card><CardHeader title="Claims by status" eyebrow="Operational distribution" /><div className="status-matrix">{data.claimsByStatus.map((row) => <Link to={`/claims?status=${row.status}`} key={row.status}><StatusBadge value={row.status} /><strong>{row.count}</strong></Link>)}</div></Card></div>; }
