export enum DepartmentCategory {
  PHARMACY = "PHARMACY",
  LABORATORY = "LABORATORY",
  RADIOLOGY = "RADIOLOGY",
  ROOM_CHARGES = "ROOM_CHARGES",
  DOCTOR_FEES = "DOCTOR_FEES",
  OT_CHARGES = "OT_CHARGES",
  CONSUMABLES = "CONSUMABLES",
  OTHER = "OTHER",
}
