import { useMemo, useState } from "react";
import { EmptyState } from "../ui/EmptyState";
export interface Column<T> { key: string; header: string; cell: (row: T) => React.ReactNode; sortValue?: (row: T) => string | number; className?: string; }
export function DataTable<T>({ rows, columns, getRowId, onRowClick, compact = true }: { rows: T[]; columns: Column<T>[]; getRowId: (row: T) => string; onRowClick?: (row: T) => void; compact?: boolean }) {
  const [sortKey, setSortKey] = useState<string>(columns[0]?.key ?? ""); const [direction, setDirection] = useState<"asc" | "desc">("asc"); const [visible, setVisible] = useState<Record<string, boolean>>(() => Object.fromEntries(columns.map((c) => [c.key, true])));
  const sorted = useMemo(() => [...rows].sort((a, b) => { const col = columns.find((c) => c.key === sortKey); if (!col?.sortValue) return 0; const av = col.sortValue(a); const bv = col.sortValue(b); return (av > bv ? 1 : av < bv ? -1 : 0) * (direction === "asc" ? 1 : -1); }), [rows, columns, sortKey, direction]);
  const shown = columns.filter((c) => visible[c.key]);
  return <div className="table-shell"><div className="table-tools"><div className="column-toggles">{columns.map((c) => <label key={c.key}><input type="checkbox" checked={visible[c.key]} onChange={(e) => setVisible((v) => ({ ...v, [c.key]: e.target.checked }))} />{c.header}</label>)}</div><button className="link-button" type="button" onClick={() => window.print()}>Export / Print</button></div><table className={compact ? "data-table compact" : "data-table"}><thead><tr>{shown.map((c) => <th key={c.key} className={c.className}><button type="button" onClick={() => { setSortKey(c.key); setDirection((d) => sortKey === c.key && d === "asc" ? "desc" : "asc"); }}>{c.header}{sortKey === c.key ? (direction === "asc" ? " ↑" : " ↓") : ""}</button></th>)}</tr></thead><tbody>{sorted.map((row) => <tr key={getRowId(row)} onClick={() => onRowClick?.(row)}>{shown.map((c) => <td key={c.key} className={c.className}>{c.cell(row)}</td>)}</tr>)}</tbody></table>{rows.length === 0 && <EmptyState />}</div>;
}
