export enum Roles {
  SUPER_ADMIN = "SUPER_ADMIN",
  ADMIN = "ADMIN",
  CLAIM_MANAGER = "CLAIM_MANAGER",
  CLAIM_EXECUTIVE = "CLAIM_EXECUTIVE",
  ACCOUNTANT = "ACCOUNTANT",
  PHARMACIST = "PHARMACIST",
}
