import { useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { claimsApi } from "../../api/services";
import { allowedTransitions, canReopen, canRoleTransition } from "../../constants/workflow";
import { useAuthStore } from "../../store/auth.store";
import type { Claim, ClaimStatus } from "../../types/domain";
import { labelize } from "../../utils/format";
import { Button } from "../ui/Button";
import { Modal } from "../ui/Modal";
import { ErrorPanel } from "../ui/ErrorPanel";
export function WorkflowActionsPanel({ claim }: { claim: Claim }) { const user = useAuthStore((s) => s.user); const qc = useQueryClient(); const [target, setTarget] = useState<ClaimStatus>(); const [remarks, setRemarks] = useState(""); const transitions = allowedTransitions(claim.type, claim.status).filter((status) => user ? canRoleTransition(user.role, status) : false); const mutation = useMutation({ mutationFn: ({ status, reason }: { status: ClaimStatus; reason: string }) => claimsApi.transition(claim._id, { toStatus: status, remarks: reason, performedBy: user?._id }), onSuccess: () => { qc.invalidateQueries({ queryKey: ["claim", claim._id] }); qc.invalidateQueries({ queryKey: ["timeline", claim._id] }); setTarget(undefined); setRemarks(""); } }); const closed = claim.status === "CLOSED"; return <aside className="action-panel"><p className="eyebrow">Workflow controls</p><h2>{labelize(claim.status)}</h2>{closed && !canReopen(user?.role) && <div className="restriction">Closed claims are locked. Only SUPER_ADMIN may reopen with audit reason.</div>}{closed && canReopen(user?.role) && <Button variant="danger" onClick={() => setTarget("DRAFT")}>Reopen with audit reason</Button>}{!closed && transitions.map((status) => <Button key={status} onClick={() => setTarget(status)} variant={status === "CLOSED" ? "danger" : "primary"}>{labelize(status)}</Button>)}{transitions.length === 0 && !closed && <div className="restriction">No permitted frontend workflow actions for your role at this status.</div>}<Modal open={Boolean(target)} title="Audit confirmation required" onClose={() => setTarget(undefined)}><div className="modal-body"><p>Confirm transition to <strong>{labelize(target)}</strong>. The backend will enforce workflow validity and this reason supports audit review.</p><textarea className="input textarea" value={remarks} onChange={(e) => setRemarks(e.target.value)} placeholder="Audit reason / operational remarks" />{remarks.length > 0 && remarks.length < 5 && <small className="field-error">Enter at least 5 characters.</small>}{mutation.isError && <ErrorPanel error={mutation.error} />}<div className="modal-actions"><Button variant="secondary" onClick={() => setTarget(undefined)}>Cancel</Button><Button disabled={!target || remarks.length < 5 || mutation.isPending} onClick={() => target && mutation.mutate({ status: target, reason: remarks })}>{mutation.isPending ? "Updating..." : "Confirm transition"}</Button></div></div></Modal></aside>; }
